pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Backend Test') {
            steps {
                sh '''
                    docker run --rm \
                    -v "$WORKSPACE/back-end:/app" \
                    -w /app \
                    maven:3.9-eclipse-temurin-17 \
                    mvn test
                '''
            }
        }

    }
}
